# Generated by Django 4.0 on 2022-03-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='본문')),
                ('view_count', models.IntegerField(blank=True, default=None, null=True, verbose_name='조회수')),
                ('like_count', models.IntegerField(blank=True, default=None, null=True, verbose_name='추천수')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='게시글 삭제 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='닉네임')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('content', models.TextField(default='', verbose_name='댓글 내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='댓글 삭제 여부')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='게시글')),
            ],
        ),
    ]
